### ISSUE TITLE
Clean Links generates wrong URL for GitHub commit

### ISSUE THREAD

**Issue by Anthony-Gaudino** [diegocr/CleanLinks#108]
On GitHub, at the following repository commits history page: https://github.com/vwochnik/jekyll-language-plugin/commits/master

Upon clicking on the `updated example site` commit, the generated URL is `http://www.xn--=wwww12;wxsso4{%1eo-s2a72dzjnb6fzd7d0a6k0a4d7226l.com/` instead of `https://github.com/vwochnik/jekyll-language-plugin/commit/59123ed3d3d7079ef26bfc23d40f7fb9c0e80eb0` and then I can't access the commit without having to disable **Clean Links** first.

**Comment by diegocr** [comment]
Interesting bug, it is choking with the sha1, picking the `d3d3...` part which is "www" base64-encoded.

Should be an easy fix, thank for reporting it!
