### ISSUE TITLE
This extension seems to break Google reCAPTCHA

### ISSUE THREAD

**Issue by osoba** [diegocr/CleanLinks#116]
Try, for example, opening http://tinychat.com/randomasffsdggf (it's just a random chatroom). It should require you to fill in a captcha before letting you in. If you have CleanLinks enables in Firefox it just displays "Cannot contact reCAPTCHA. Check your connection and try again." After disabling the extension and reloading the page, the captcha works fine.

**Comment by diegocr** [comment]
Right-click the CleanLinks toolbar button, you'll see a list of the URL it did cleared. Find the one for reCAPTCHA and white-list it, reload the website afterwards and you should no longer get the issue.
