### ISSUE TITLE
PLEASE stop "cleaning" pure text that is not actual a href html

### ISSUE THREAD

**Issue by wolftune** [diegocr/CleanLinks#119]
If I am typing some plain text in a field and include a URL, sometimes I just click somewhere on the text, and CleanLinks goes to the URL. It wasn't even a link. Without CleanLinks, it wouldn't be clickable at all. CleanLinks needs to check whether something is a clickable link at all before it does any cleaning. URLs that aren't clickable, that are just plain text, they should not be "cleaned".

This causes me to lose work otherwise because suddenly my paragraph of typing gets "clicked" and I leave the site I'm on.

**Comment by diegocr** [comment]
Hello, go to the settings and disable _"Catch TextLinks"_, this should do it.

**Comment by wolftune** [comment]
Thanks!
