### ISSUE TITLE
[FF Nightly] Changes in nsIIOService

### ISSUE THREAD

**Issue by Halibut80** [diegocr/CleanLinks#121]
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1254752">1254752 – Remove deprecated functions from nsIIoservice</a>
Errors in console:
```
this.ios.newChannel is not a function browser.js:320:0
cleanlinks.cl() browser.js:320
i$.getLink() bootstrap.js:78
i$.observe() bootstrap.js:182
```

**Comment by diegocr** [comment]
Thanks @Halibut80 for bringing that to my attention, i'll look into it right away.
