### ISSUE TITLE
"little extension"

### ISSUE THREAD

**Issue by IceLancerSR** [diegocr/CleanLinks#129]
Your addon is working as advertised! But how about little extension? Make it work for selected links as well. Not just one copy link? Or at least to intercept other addons "copy selected links" and fix their paths?

    Edit review
    Delete review

by Diego Casorran (Developer) on May 30, 2016 · permalink · translate

What do you mean by "little extension"?

Enabling the "http observer" option you can make CleanLinks intercept pretty much every link loaded by the browser, if that's what you want - you may find you would need to whitelist several sites, though.

---
What i ment to say is that ur addon grabs and fixes links that are visible.and is attaching to process "copy link"
But when multiple links are masked behind format
 [url=urlx]name[/url]
 [url=urly]name[/url]
one has to use separate addon for actually loading those links.
But all those addons are grabbing broken links in format:
redirect?z=https%3A%2F%2Fmega.nz%2F%23%213c4
Actuall code is
redirect?z=http://mega.nz/#!3c4

ur addon does not intercept those.
Thats what i asked could it be possible to intercept them and fix?

**Comment by diegocr** [comment]
`redirect?z=https%3A%2F%2Fmega.nz%2F%23%213c4`

Actually, that is not a broken link, it's just URL-encoded, which in fact is a requirement for nested links in URLs. You may won't see links that way in the browser's url bar, but rather when copying them to clipboard, which doesn't mean they're broken, unless i'm missing something...

`ur addon does not intercept those.`

Certainly it is not the purpose of the add-on cleaning arbitrary links in BBcode format for example, rather when they're going to be loaded by the browser or through the copylink-controller (context-menu), other than that i think i'd need a real-world scenario to know how CleanLinks could possibly deal with your feature request.

**Comment by IceLancerSR** [comment]
Thanks for listening.
But i ended up making batch script to clean links from those signs..as i need "clean links"
Your addon is not made for handling multiple links and i understand.
Thank you for your time And a very good Addon!
