### ISSUE TITLE
Lost Settings since browser beta 50.x  (fixed)

### ISSUE THREAD

**Issue by GitCurious** [diegocr/CleanLinks#157]
I`m actually using CyberFox, but between beta49 and beta50.x

Cleanlinks settings have disappeared from the settings page.

**Has anyone else noticed this with Firefox recently ?**

(putting the settings back in manually, then restarting the browser loses them again)

**Comment by diegocr** [comment]
Please check the browser-console for any related error pointed there.

(In Firefox is opened using ctrl+shift+j)

**Comment by GitCurious** [comment]
Hello Diego

_I do not see any errors in the console. Edit: see below - new post_

CL appears to be working - but the fields on the settings page are empty.

My settings are still there in my prefs.js file.

I reinstalled Cyberfox beta v49 and all was back to normal, when I installed beta v50.x the settings were empty again !

(the browser profile is the same for all versions of the browser I install)

# 

All the normal "Logging" messages in the console are there, for example:

"Clean Links Message @ 2016-10-11T18:20:01.530Z

> cleanlinks-cltrack
> http://www.imdb.com/title/tt6115034/?ref_=nm_flmg_act_1
> http://www.imdb.com/title/tt6115034/
> LOG@bootstrap.js:20:11
> i$.observe@bootstrap.js:187:5
> cleanlinks.cl@browser.js:372:4
> cleanlinks.edl@browser.js:452:9
> "

~

Also, when I press the "Reset Options" button - all the fields remain empty.
The default settings do not appear.

**Comment by GitCurious** [comment]
I have just noticed something that may be related ?

```
xS.bootstrapScopes is undefined  browser.js:28
    <anonymous> resource://cleanlinks/browser.js:28:1
    <anonymous> resource://cleanlinks/browser.js:15:2
    global.loadSubScript jar:file:///E:/Cyberfox/extensions/%7B158d7cb3-7039-4a75-8e0b-3bd0a464edd2%7D.xpi!/bootstrap.js:333:2
    loadIntoWindow jar:file:///E:/Cyberfox/extensions/%7B158d7cb3-7039-4a75-8e0b-3bd0a464edd2%7D.xpi!/bootstrap.js:462:2
    startup/</<.onBuild jar:file:///E:/Cyberfox/extensions/%7B158d7cb3-7039-4a75-8e0b-3bd0a464edd2%7D.xpi!/bootstrap.js:838:16
    CustomizableUIInternal.wrapWidgetEventHandler/aWidget[aEventName] resource://app/modules/CustomizableUI.jsm:2421:16
    CustomizableUIInternal.buildWidget resource://app/modules/CustomizableUI.jsm:1347:16
    CustomizableUIInternal.getWidgetNode resource://app/modules/CustomizableUI.jsm:900:16
    CustomizableUIInternal.buildArea resource://app/modules/CustomizableUI.jsm:724:32
    CustomizableUIInternal.registerToolbarNode resource://app/modules/CustomizableUI.jsm:677:9
    this.CustomizableUI.registerToolbarNode resource://app/modules/CustomizableUI.jsm:3064:5
    _init chrome://browser/content/customizableui/toolbar.xml:85:11
    onReadyStateChange chrome://browser/content/customizableui/toolbar.xml:37:15
```

**Comment by diegocr** [comment]
That is a harmless caught exception: https://github.com/diegocr/CleanLinks/blob/776f0b6c12cde0b0004590c281daf5b4900e6f42/browser.js#L31

> the browser profile is the same for all versions of the browser I install

I think it's probably a bad idea using the same profile when downgrading the browser version.

You may want to try a [_"Refresh"_](http://mzl.la/15sSfJR) over that profile, I suppose it'll be the same under Cyberfox.

(if you didn't did that process before, read carefully the page regarding what it does, you likely want to make a backup of your prefs.js file to copy&paste/restore any add-on configuration later)

**Comment by GitCurious** [comment]
OK thanks, I can ignore that message.

As it was late last night, I forgot to do the most obvious thing that I _should_ have done first - test with a new\clean profile (doh!)

-Cyberfox v50.05b 
-with an empty clean profile 
-CleanLinks v2.8a1

Results are the same - the text fields on the Cleanlinks settings page are empty.
Clicking "Reset Options" changes the radio buttons but the text fields are always empty.

The default settings exist in the new user.js file but the settings page is not filled with any data.

I see only one message in the console when trying to apply settings:
`ReferenceError: Preferences is not defined[Learn More] setting.xml:303:11
    valueToPreference chrome://mozapps/content/extensions/setting.xml:303:11
    inputChanged chrome://mozapps/content/extensions/setting.xml:100:13
    oninput about:addons:1:1`
I do not know if this is related.

~

Also, CleanLinks **v2.71** shows the same problem with Cyberfox 50.05b

(CleanLinks 2.71 DOES work in **Firefox** 50.0**1**b)

I`m wondering if anyone else has seen the same unusual behaviour - or if it just a problem with my specific setup.
