### ISSUE TITLE
Is this add-on obsoleted by Firefox itself?

### ISSUE THREAD

**Issue by jawz101** [diegocr/CleanLinks#163]
Specifically these about:config entries

network.http.referer.XOriginPolicy
network.http.referer.spoofSource
network.http.referer.trimmingPolicy
network.http.sendRefererHeader
network.http.enablePerElementReferrer
network.http.sendSecureXSiteReferrer

**Comment by dartraiden** [comment]
[HTTP referer](https://en.wikipedia.org/wiki/HTTP_referer) ≠[URL parameters](http://www.bytefive.com/blogs/understanding-utm_source-utm_medium-and-utm_campaign)

**Comment by Atavic** [comment]
_About:config_ tells how the browser acts with HTTP referrering.
_CleanLinks_ acts on the link parameters, something Firefox itself can't do by default.
