### ISSUE TITLE
Incorrect resolve of any website with a referrers using tokens with valid URLs as the referrer ID

### ISSUE THREAD

**Issue by TheWatcherer** [diegocr/CleanLinks#65]
Incorrectly resolving web addresses where tokens are used by referrers such as ccbill (though this is the case for referrers that use a valid URL as part of the referrer id token).

example:
http://www.whateversite.com/sites?url=http://freepart.freestuffsite.com/freestuff_you_want_to_browse.html?ccbill_id=1234567&sitelink=http://freestuffsite.com&var1=whateversite

resolves to:
http://freestuffsite.com
and not to the actual link:
http://freepart.freestuffsite.com/freestuff_you_want_to_browse.html

**Comment by diegocr** [comment]
What version are you using?

Using the 2.7a1 version here on Github i'm getting:

```sh
Clean Links Message @ 2015-01-09T21:00:47.047Z
> cleanlinks-cltrack
> http://www.whateversite.com/sites?url=http://freepart.freestuffsite.com/freestuff_you_want_to_browse.html?ccbill_id=1234567&sitelink=http://freestuffsite.com&var1=whateversite
> http://freepart.freestuffsite.com/freestuff_you_want_to_browse.html?ccbill_id=1234567
LOG@bootstrap.js:19:11
i$.observe@bootstrap.js:131:1
cleanlinks.cl@browser.js:355:1
cleanlinks.edl@browser.js:435:9
```
So, please give that version a try (installing it by using GitHubExtIns)

**Comment by TheWatcherer** [comment]
I was using latest public release 2.6.1
Installed v2.7a1 (took a while until i figured out you were talking about the new master file :p )

This seems to fix that one, but not sure if this will be fixed for all referrers or links that contain 3 valid URLs.
