### ISSUE TITLE
breaking user styles

### ISSUE THREAD

**Issue by atomGit** [diegocr/CleanLinks#69]
CL 2.6.1.0
FF 34

i'm setting the color of visited links for some domains with some CSS and Clean Links is breaking this functionality (with or without Highlight Style enabled)

**Comment by diegocr** [comment]
How these user-styles are loaded?

Also, please try to install the version here on Github and provide the browser's console debug output.

**Comment by atomGit** [comment]
you can close this issue - i use a GM script to clean links now

**Comment by diegocr** [comment]
Aha.... I highly doubt a GreaseMonkey script can achieve the same than an extension, but as long it fit your needs.
