### ISSUE TITLE
Yandex

### ISSUE THREAD

**Issue by crisalis** [diegocr/CleanLinks#71]
For http://www.yandex.com/ search results (also the https version, and the same for yandex.ru, .ua, .by, .kz and .com.tr), it returns to the same search page instead of cleaning their redirection.

(Yandex is an important Russian search engine.)

**Comment by diegocr** [comment]
You're correct, I did a quick test and i've got:

```bash
Clean Links Message @ 2015-01-09T19:46:14.998Z
> cleanlinks-cltrack
> http://www.yandex.com/clck/jsredir?from=www.yandex.com%3Byandsearch%3Bweb%3B%3B&text=halo&uuid=&state=AiuY0DBWFJ4ePaEse6rgeAjgs2pI3DW9Iuwyq9ogZlJoYfcMnJ3JahAxAuGjA1XDpPzL1UBUdPx1qwouQfe_QEtQDEzL1jNVjcbrwNa9k7MlSvIFl5ndvRj0qcgxyK3u3QZyXLvoyXdCflcTV4SMAoWrOkkv6DNxN5WNMnJj-A0pba-itNG3IA1W4i1WiSlCBpGH0HAdVSTEs0vSgRaNa_bKiiphyCpSXTDTYvE-EmP_hWtLOiz9qaKUZTqQRExY&data=UlNrNmkWktYejR0eWJFYk1LdmtxalR0OTdVcHpQOTJhMMnpCY0lfQ1hleV9LMkgwbjUzek1PUUZzYVl2NnODhpdU9SSi1EdW1lWEo0eU9IeFdNR009NRU1h&b64e=2&sign=e8f584a336e62bafcba4d1d3d7&keyno=0&l10n=en&ref=https%3A%2F%2Fwww.yandex.com%2Fyandsearch%3Flr%3D87%26text%3Dhalo&cts=1420832774853&mc=3.7871439606981414
> https://www.yandex.com/yandsearch?lr=87&text=halo
LOG@bootstrap.js:19:11
i$.observe@bootstrap.js:131:1
cleanlinks.cl@browser.js:355:1
cleanlinks.edl@browser.js:435:9
```
Hence, you have to add **yandsearch** to the _Skip Links..._ option, like this:

![150209195152](https://cloud.githubusercontent.com/assets/734313/5686228/90ab2430-9841-11e4-8a84-be14af1dd039.gif)

**Comment by crisalis** [comment]
OK, but I meant if you could fix Yandex search links in the same way as Google search links, not just disable the add-on for those links. Like using the href attribute or something.
