### ISSUE TITLE
Something odd in iCloud Mail?

### ISSUE THREAD

**Issue by rhky** [diegocr/CleanLinks#73]
With Clean Links enabled: When I click on Reply in iCloud Mail, this is the link that opens:
http://www.message.com/VIP/VIP_82F2C980-8079-429C-8CC4-F22476C90DB1/71277
With CL disabled: https://www.icloud.com/message/current/en-us/#reply?guid=message%3A%2FVIP%2FVIP_82F2C980-8079-429C-8CC4-F22476C90DB1%2F71277

What in the world is going on? First, where is that rogue link to message.com lurking? With Clean Links disabled or uninstalled, I never see it. It seems to *come with* Clean Links! Huh? Thanks for taking a look!

![messagecom](https://cloud.githubusercontent.com/assets/8313136/5683222/1b074e36-97f4-11e4-9fc3-9a173c4234a8.PNG)

**Comment by diegocr** [comment]
Apparently it comes from this chunk of the original link:

`?guid=message%3A%2FVIP%2FVIP...`

That url-decoded becomes:

`?guid=message:/VIP/VIP...`

And CleanLinks extracts the _"guid"_ parameter value and loads it as an URL, then Firefox thinks you misspelled the hostname and automaically changes it to _"message.com"_

Odd indeed, going to fix it right away, thanks for reporting it!

**Comment by rhky** [comment]
Great response, thanks. For us paranoid types, that was worrisome. But what's with Firefox algorithmically deciding what I must have meant? I need to find out how to turn that off. But first I'm going to find your donate-ware button. [Wish you had a Safari extension.]

**Comment by rhky** [comment]
Actually -- this behavior has not changed in the least. This is not fixed.
