### ISSUE TITLE
Please add StumbleUpon.com

### ISSUE THREAD

**Issue by doomkrad** [diegocr/CleanLinks#85]
Here is a sample:
http://www.stumbleupon.com/su/2hPgtj/qpm@SPqL:2q_isql9/www.psmag.com/health-and-behavior/psychology-of-long-missions-in-space

Many thanks!

**Comment by diegocr** [comment]
Hello @doomkrad, if you don't want stumbleupon links from being cleaned, you can right-click the toolbar button and whitelist the domain. This should be more feasible than whitelisting it for everybody.
