### ISSUE TITLE
CleanLinks breaks the Join link of StackExchange sites

### ISSUE THREAD

**Issue by pietsch** [diegocr/CleanLinks#96]
This add-on breaks the Join link on StackExchange sites but replacing it with a link to the current page. Unmodified, the URL is something like this (and it should not be modified):

https://academia.stackexchange.com/users/join?returnurl=https%3a%2f%2facademia.stackexchange.com%2fFOO

With CleanLinks active, it becomes something like this:

https://academia.stackexchange.com/FOO

**Comment by diegocr** [comment]
Hi @pietsch, have you tried right-clicking the toolbar button and whitelisting `academia.stackexchange.com`?

**Comment by pietsch** [comment]
No longer using the plugin. It was useless with Twitter, which was my main reason to use it.

**Comment by diegocr** [comment]
Heh, okay.
